#!/bin/sh

repeat_seconds=300

if test $# = 3
then
    url=$1
    regexp=$2
    email_address=$3
else
    echo "Usage: $0 <url> <regex>" 1>&2
    exit 1
fi

while true
do
    if curl --silent "$url"|grep -E "$regexp" > /Users/afterlife/Documents/test
    then
        echo "Generated by $0" |
        mail -s "$url now matches $regexp" "$email_address"
        exit 0
    fi
    sleep $repeat_seconds
done