#!/usr/bin/env dash

#check .girt exists
if ! test -d .girt/
then
    echo "girt-show: error: no .girt directory containing girt repository exists";
    exit 1;
fi

#test for format num:repository
content=$1;
match=`echo $1|egrep '^[0-9]*:.*'`;
if test "$match" = ""
then
    echo "girt-show: error: invalid object $1";
    exit 1;
fi

#get the number before : and fileaname after :.
num=`echo $1|sed 's/:.*$//g'`;
filename=`echo $1|sed 's/^.*://g'`;

#test if the required num beyond maximum repository num
max_num=`ls -c .girt/repository|wc -l|sed 's/ //g'`;
max_repo=$(($max_num - 1));
current_branch=`cat .girt/current_branch`;
#whatever num is "" or a number,we all should test if the file does exist in index or repository we ask for.
if test "$num" = ""
then
    contain=`ls .girt/branch/$current_branch/index/$filename 2>/dev/null`;
    if test "$contain" != ""
    then
        cat ".girt/branch/$current_branch/index/$filename";
    else
        echo "girt-show: error: '$filename' not found in index";
    fi
else
    if test $num -gt $max_repo
    then
        echo "girt-show: error: unknown commit '$num'";
        exit 1;
    else
        contain=`ls .girt/repository/$num/$filename 2>/dev/null`;
        if test "$contain" != ""
        then
            cat ".girt/repository/$num/$filename";
        else
            echo "girt-show: error: '$filename' not found in commit $num";
        fi
    fi
fi
