#!/bin/dash

#check .girt exists
if [ -d .girt/ ]
then
    # current .girt exists
    :
else
    # current .girt does not exist ----> print error
    echo "girt-rm: error: no .girt directory containing girt repository exists";
    exit 1;
fi

# There are 2 argvs in remove the first is force the second is cached
force_flag=0
cached_flag=0
input_argv=$1
current_branch=$(cat .girt/current_branch)
filelist=$@
force_option="--force"
cached_option="--cached"

# I just wondered that is there a situation which has force and cached at the same time
# Notice: Whether there is a situation that
# check the option of --force
if [ "$input_argv" = "$force_option" ]
then
	force_flag=1
	# How to use shift in the shell
	# this shift is for moving to next one
	# Source: https://unix.stackexchange.com/questions/174566/what-is-the-purpose-of-using-shift-in-shell-scripts
	shift
fi

# This is to check the option of --cached
if [ "$input_argv" = "$cached_option" ]
then
	cached_flag=1
	# See the previous annotation
	shift
fi

#first check all files are in index
for filename in "$filelist"
do	
	# file exist
	if [ -e .girt/branch/$current_branch/index/$filename ]
	then
		# continue
		:
	else
		# file not exists ----> exit and print error
		echo "girt-rm: error: '$filename' is not in the girt repository"
		exit 1
	fi
done

# checking the flag of force and cached
# checking the flag for force
if [ $force_flag -eq 1 ]
then
	# This is from webcms3
	# --force option overrides this, and will carry out the removal even if the user will lose work.
	# if flag = 1 remove file in the index dir
	for file in "$filelist"
	do
		current_del_directory=".girt/branch/$current_branch/index/$file"
		rm -r "$current_del_directory"
	done
fi
# checking the flag for cached
if [ $cached_flag -eq 0 ]
then
	# This is from webcms3
	# --cached option, the file is removed only from the index, and not from the current directory.
	# if no catch flag in the previous operation, remove the files in the current directory
	for file in "$filelist"
	do	
		# if exist, then remove the file
		if [ -e  $file ]
		then 
			# remove the file in the filelist
			rm "$file" 
		fi
	done
fi

# these part of codes are similar to girt-commit
change_counter=1
change_number=$(ls -c .girt/repository|wc -l|sed 's/ //g')
latest_modified_branch=$(ls .girt/branch/$current_branch/repository|sort|tail -n 1)
# checking if the content in files are different from index directory and current directory or index directory and repository
for file in "$filelist"
do
	# checking whether the file is exist or not
	if [ -e $file ]
	then
		# Using the difference to check the difference
		# Source: https://www.geeksforgeeks.org/diff-command-linux-examples/
		current_index_difference=$(diff $file .girt/branch/$current_branch/index/$file|wc -w)
		if [ $current_index_difference -gt 0 ]
		then
			if [ $change_number -ne 0 ]
			then
				if [ -e  .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
				then
					# using the word counter provided by wc
					# Source: https://explainshell.com/explain?cmd=wc+-w
					current_repository_difference=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w);
					if [ $current_repository_difference -gt 0 ]
					then
						change_counter=0;
					fi
				else
					change_counter=0;
				fi
			else
				if [ $current_index_difference -gt 0 ]
				then
					change_counter=0
				else
					:
				fi
			fi
		fi
	else
		:
	fi
	if [ $change_counter -ne 0 ]
	then
		# has similarity
		:
	else
		# totally different
		echo "girt-rm: error: '$file' in index is different to both working file and repository"
		exit 1
	fi
done

# Getting the cached flag and remove the file in the directory
# check both cached flag and change counter 
if [ $change_counter -eq 1 ]
then
	if [ $cached_flag -eq 1 ]
	then
		# removed the file in the index directory
		for file in "$filelist"
		do
			current_del_directory=".girt/branch/$current_branch/index/$file"
			rm -r "$current_del_directory"
		done
	fi
fi

# no changes of flags, check whether the index files are committed
if [ $force_flag -eq 0 ]
then
	if [ $cached_flag -eq 0 ]
	then
		for file in "$filelist"
		do
			# checking the file is exist or not
			if [ -e $file ]
			then
				# compart the current file with the index dir
				current_dir_difference=$(diff $file  .girt/branch/$current_branch/index/$file|wc -w)
				if [ $current_dir_difference -ne 0 ]
				then
					if [ $change_number -gt 0 ]
					then
						if [ -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
						then
							current_repo_difference=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w)
							if [ $current_repo_difference -eq 0 ]
							then
								echo "girt-rm: error: '$file' in repository is different to working file"
								exit 1
							fi
						fi
					fi
				else
					# current_dir_difference eq 0
					if [ $change_number -eq 0 ]
					then
						echo "girt-rm: error: '$file' has changes staged in the index"
						exit 1
					else
						#if the latest repository does not have the file ,then quit
						if [ ! -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
						then
							echo "girt-rm: error: '$file' has changes staged in the index"
							exit 1
						else
							#does not the same file
							difference_repository=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w)
							if [ $difference_repository -gt 0 ]
							then
								echo "girt-rm: error: '$file' has changes staged in the index"
								exit 1
							fi
						fi
					fi
				fi
			fi
		done
		for file in "$filelist"
		do
			current_del_directory=".girt/branch/$current_branch/index/$file"
			# remove
			rm -r "$current_del_directory"
			# exist then delete
			if [ -e $file ]
			then
				rm -r "$file"
			fi
		done
	fi
fi
