#!/bin/dash

# .girt
# |-- All repository
# |-- branch
#     |-- master branch
#         |-- index
#         |-- repository
#     |-- new branch
# |-- head(the location on branch) (Not mention in this assignment)
# |-- commit
#     
#

# version control system of Git
# Source: https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control
# How to use git
# Source: https://ourcodingclub.github.io/tutorials/git/
# How to understand the structure of git
# Source : https://homes.cs.washington.edu/~mernst/advice/version-control.html

# create the dir call girt
if [ -d ".girt" ]
then
    echo "girt-init: error: .girt already exists"
	exit 1
else 
    :
fi

# if the directory is not exists
# create the dir called .girt
mkdir ".girt"
echo "master" > .girt/current_branch;

# create the master branch as git
# U can find the structure of git from the following website
# Source: https://digitalvarys.com/git-basics-and-beginners-guide/
mkdir .girt/repository
# the location of the file on the branch(may not use)
mkdir .girt/head
# comit the staged files
mkdir .girt/commit

# branch
mkdir .girt/branch
mkdir .girt/branch/master
# Therefore, we need to create the index file in the repository
mkdir .girt/branch/master/index
# The repository in the master branch
mkdir .girt/branch/master/repository



# This is the same from the instruction
echo "Initialized empty girt repository in .girt";
