#!/bin/dash

# Checking the current directory is exist or not
if [ -d .girt/ ]
then
    # if exist continue
    :
else
    # not exist raising error
    echo "girt-branch: error: no .girt directory containing girt repository exists"
    exit 1
fi

# This part of code is similar to  he girt-status part
# This is used to check the log file is exist or not
log_directory=".girt/branch/$current_branch/log"
if [ -e $log_directory ]
then
    :
else
    # if there is no commit, the girt-commit will not create log file
    # Do not forget to change is to branch
    echo "girt-branch: error: your repository does not have any commits yet"
    exit 1
fi

current_branch=$(cat .girt/current_branch)
# In the girt-branch part
# there are 3 situations
# The first one is show all branches
# The seconde one is delete a branch
# The third one creating a new branch
if [ "$#" -ne 0 ]
then
    #check the branch option -d and branch name
    if [ "$1" = "-d" ]
	then
        # in the -d option need to delete the branch
        input_branch_name=$2
		# check for the valid branch name
        # the branch name is like b2 which has both characters and numbers
		branch_match_with_char_num=$(echo $input_branch_name|egrep '^[a-zA-Z0-9][a-zA-Z0-9\.\-\_]+*$')
		branch_match_without_number=$(echo $input_branch_name|egrep '^[0-9]*$')
        # this means the the branch_match_with_char_num is not empty
        # branch_match_without_number is empty
        if [ "$branch_match_string1" != "" ] 
		then
            # eliminating the pure number of branch name
			if [ "$branch_match_string2" = "" ]
			then
                # the branch name is correct
            fi
        else
            # the branch is invalid
        fi
    else
        # in without the -d option check the create a new branch
    fi
else
    #print the branch name
fi