#!/bin/dash
# 3 April local coding and testing on MacOS

# filelist="$@"

# for i in "$@"
# do
#     file_array=($i)
# done

# check .girt directory is exist or not
if [ -d .girt/ ]
then
    :
else
    echo "girt-add: error: girt repository directory .girt not found" >/dev/stderr
    exit 1
fi

# check the validation of the file name
for file in "$@"
do
    match_regex=$(echo "$file" | egrep "^[a-zA-Z0-9][a-zA-Z0-9\.\-\_]*$")
    if [ "$match_regex" != "" ]
    then
        :
    else
        echo "girt-add: error: invalid filename '$file'" > /dev/stderr
        exit 1
    fi
done

current_branch=$(cat .girt/current_branch)

# check the file is located in the directory
for file in "$@"
do
    current_file_index=$(ls $file 2>/dev/null) 
    current_file_dir=$(ls .girt/branch/$current_branch/index/$file 2>/dev/null)
    if [ "$current_file_dir" = "" ]
    then 
        if [ "$current_file_index" != "" ]
        then
            :
        else
            echo "girt-add: error: can not open '$file'" > /dev/stderr
            exit 1
        fi
    fi
done

# copy the file to the branch
# this is the girt-add operation
for file in "$@"
do
    current_file_index=$(ls $file 2>/dev/null)
    if [ "$current_file_index" = "" ]
    then
        # Differen kinds of deletion can seek the following link
        # Source: https://linuxize.com/post/how-to-remove-files-and-directories-using-linux-command-line/
        rm -r ".girt/branch/$current_branch/index/$file"
    else
        # using the copy
        # Source: https://www.rapidtables.com/code/linux/cp.html
        cp -r "$file"  .girt/branch/$current_branch/index/ 
    fi
done